import { z } from "zod";

// --- Zod Schemas ---

// BudgetImage schema (used in sections and locations)
export const budgetImageSchema = z.object({
    id: z.string(),
    section_id: z.string().optional(),
    location_id: z.string().optional(),
    block_id: z.string().optional(),
    url: z.string(),
    composed_url: z.string().optional(),
    width: z.number(),
    height: z.number(),
    order_index: z.number().optional(),
    annotations: z.array(z.record(z.string(), z.unknown())).optional(),
});

export type BudgetImage = z.infer<typeof budgetImageSchema>;

export const budgetItemSchema = z.object({
    id: z.string().optional(),
    section_id: z.string().optional(), // Linked when added to specific section (legado)
    block_id: z.string().optional(),   // Linked to budget_block type='section' (compositor)
    product_id: z.union([z.string(), z.object({ id: z.string().optional(), description: z.string().optional(), name: z.string().optional(), unit: z.string().optional(), image: z.string().optional() })]),
    quantity: z.number().min(1, "Quantidade mínima é 1"),
    unit_price: z.number().min(0),
    labor_cost: z.number().min(0).default(0), // Mão de obra unitária (copiada do produto)
    total: z.number().min(0),
    notes: z.string().optional(),
    group_id: z.string().optional(),   // ID do grupo de origem (se veio de um grupo)
    group_name: z.string().optional(), // Nome do grupo (desnormalizado para exibição)
});

export const budgetSectionSchema = z.object({
    id: z.string().optional(),
    location_id: z.string().optional(),
    budget_id: z.string().optional(),
    name: z.string().min(1, "Nome do trecho é obrigatório"),
    description: z.string().optional(),
    order_index: z.number().default(0),
    items: z.array(budgetItemSchema).optional(),
    images: z.array(budgetImageSchema).optional(),
});

export const budgetLocationSchema = z.object({
    id: z.string().optional(),
    budget_id: z.string().optional(),
    name: z.string().min(1, "Nome do local é obrigatório"),
    description: z.string().optional(),
    order_index: z.number().default(0),
    sections: z.array(budgetSectionSchema).optional(),
    images: z.array(budgetImageSchema).optional(),
});

export const budgetSchema = z.object({
    id: z.string().optional(),
    client_id: z.string().min(1, "Cliente é obrigatório"),
    code: z.string().optional(), // Generated by server
    title: z.string().min(1, "Título é obrigatório"),
    description: z.string().optional(),
    status: z
        .enum(['draft', 'finalized', 'sent', 'approved', 'rejected'])
        .default('draft'),
    total_value: z.number().default(0),

    // Numeração hierárquica legada (ex: seção 5 → locais 5.1, 5.2)
    section_number: z.number().int().min(1).default(1),

    // Compositor: true = usa árvore de blocos dinâmicos; false = aba Ambientes legada
    use_compositor: z.boolean().default(false),

    // Condições Comerciais
    payment_terms: z.string().optional().default("30/60/90 dias"),
    delivery_time: z.string().optional().default("10 dias úteis após aprovação"),
    validity_days: z.number().optional().default(15),
    issue_date: z.string().optional(), // ISO string date

    // Timestamps
    created_at: z.string().optional(),
    updated_at: z.string().optional(),

    // Relations
    locations: z.array(budgetLocationSchema).optional(),
});

// --- TypeScript Types derived from Zod ---

export type BudgetItem = z.infer<typeof budgetItemSchema> & {
    // Relationships for UI display
    product_code?: string;
    product_name?: string;
    product_unit?: string;
    product_image?: string;
};

export type BudgetSection = z.infer<typeof budgetSectionSchema>;
export type BudgetLocation = z.infer<typeof budgetLocationSchema>;
export type Budget = z.infer<typeof budgetSchema>;

// Helper for UI Tree Structure
export type BudgetTree = Budget & {
    locations: (BudgetLocation & {
        sections: (BudgetSection & {
            items: BudgetItem[];
        })[];
    })[];
};
