import { z } from "zod";
import type {
    CostDisplayMode,
    LocationAssemblyMode,
    PriceAdjustmentMode,
} from "@/lib/budgets/scope-pricing";

// --- Zod Schemas ---

// BudgetImage schema (used in sections and locations)
export const annotatorViewportSchema = z.object({
    scale: z.number(),
    x: z.number(),
    y: z.number(),
});

export const budgetImageSchema = z.object({
    id: z.string(),
    section_id: z.string().optional(),
    location_id: z.string().optional(),
    block_id: z.string().optional(),
    /** Legenda para lista de figuras (obrigatória no Escopo ao adicionar foto) */
    caption: z.string().optional(),
    url: z.string(),
    composed_url: z.string().optional(),
    width: z.number(),
    height: z.number(),
    order_index: z.number().optional(),
    /** Zoom/pan do anotador (Surreal: `editor_viewport`) */
    editor_viewport: annotatorViewportSchema.nullish().optional(),
    /** Quadro de exibição no escopo (proporção tipo A4): retrato ou paisagem */
    figure_frame_orientation: z.enum(["portrait", "landscape"]).optional(),
    annotations: z.array(z.record(z.string(), z.unknown())).optional(),
});

export type BudgetImage = z.infer<typeof budgetImageSchema>;

export const budgetItemSchema = z.object({
    id: z.string().optional(),
    section_id: z.string().optional(), // Linked when added to specific section (legado)
    block_id: z.string().optional(),   // Linked to budget_block type='section' (compositor)
    product_id: z.union([z.string(), z.object({ id: z.string().optional(), description: z.string().optional(), name: z.string().optional(), unit: z.string().optional(), image: z.string().optional() })]),
    quantity: z.number().min(1, "Quantidade mínima é 1"),
    unit_price: z.number().min(0),
    labor_cost: z.number().min(0).default(0), // Mão de obra unitária (copiada do produto)
    total: z.number().min(0),
    notes: z.string().optional(),
    observation_text: z.string().optional(),
    observation_show_on_print: z.boolean().optional().default(false),
    /** Se true e `labor_cost` > 0, PDF separa equipamento vs mão de obra; se false, MO fica embutida no valor exibido. */
    labor_show_on_print: z.boolean().optional().default(false),
    observation_extra_value: z.number().optional().default(0),
    price_adjustment_mode: z.custom<PriceAdjustmentMode>().nullable().optional(),
    price_adjustment_value: z.number().optional().default(0),
    assembly_manual_value: z.number().optional().default(0),
    group_id: z.string().optional(),   // ID do grupo de origem (se veio de um grupo)
    group_name: z.string().optional(), // Nome do grupo (desnormalizado para exibição)
    /** Instância por inserção: mesmo catálogo adicionado 2x = dois blocos separados na UI */
    group_instance_id: z.string().optional(),
});

export const budgetSectionSchema = z.object({
    id: z.string().optional(),
    location_id: z.string().optional(),
    budget_id: z.string().optional(),
    name: z.string().min(1, "Nome do trecho é obrigatório"),
    description: z.string().optional(),
    order_index: z.number().default(0),
    /** Montagem por trecho (escopo); fallback ao local quando omitido. */
    assembly_mode: z.custom<LocationAssemblyMode>().optional(),
    assembly_value: z.number().optional(),
    items: z.array(budgetItemSchema).optional(),
    images: z.array(budgetImageSchema).optional(),
});

export const budgetLocationSchema = z.object({
    id: z.string().optional(),
    budget_id: z.string().optional(),
    name: z.string().min(1, "Nome do local é obrigatório"),
    description: z.string().optional(),
    order_index: z.number().default(0),
    assembly_mode: z.custom<LocationAssemblyMode>().optional().default("percent"),
    assembly_value: z.number().optional().default(0),
    sections: z.array(budgetSectionSchema).optional(),
    images: z.array(budgetImageSchema).optional(),
});

export const budgetSchema = z.object({
    id: z.string().optional(),
    client_id: z.string().min(1, "Cliente é obrigatório"),
    /** Preenchidos na listagem quando `client_id` vem com FETCH (nome e CNPJ do cliente). */
    client_name: z.string().optional(),
    client_cnpj: z.string().optional(),
    code: z.string().optional(), // Generated by server
    title: z.string().min(1, "Título é obrigatório"),
    description: z.string().optional(),
    status: z
        .enum(['draft', 'finalized', 'sent', 'approved', 'rejected'])
        .default('draft'),
    /** Orçamento de origem imediata (revisão anterior). */
    parent_budget_id: z.string().optional(),
    /** Raiz da cadeia de revisões (primeiro orçamento da proposta). */
    root_budget_id: z.string().optional(),
    /** 1, 2, 3… — ausente no orçamento original. */
    revision_number: z.number().int().min(1).optional(),
    total_value: z.number().default(0),

    // Numeração hierárquica legada (ex: seção 5 → locais 5.1, 5.2)
    section_number: z.number().int().min(1).default(1),

    // Compositor: true = usa árvore de blocos dinâmicos; false = aba Ambientes legada
    use_compositor: z.boolean().default(false),
    /** Nome do painel Compositor e título das páginas de sessão no PDF. */
    compositor_label: z.string().optional(),
    show_costs_on_print: z.boolean().optional().default(false),
    costs_display_mode: z.custom<CostDisplayMode>().optional().default("section"),

    // Condições Comerciais
    payment_terms: z.string().optional().default("30/60/90 dias"),
    delivery_time: z.string().optional().default("10 dias úteis após aprovação"),
    validity_days: z.number().optional().default(15),
    issue_date: z.string().optional(), // ISO string date

    /** Legado: um par único; novos orçamentos usam os quatro campos abaixo. */
    quote_markup_percent: z.number().optional().default(0),
    quote_discount_percent: z.number().optional().default(0),
    /** Aba Orçamento: vara/desconto % só sobre coluna equipamentos. */
    quote_markup_equipment_percent: z.number().optional().default(0),
    quote_discount_equipment_percent: z.number().optional().default(0),
    /** Aba Orçamento: vara/desconto % só sobre coluna montagem. */
    quote_markup_assembly_percent: z.number().optional().default(0),
    quote_discount_assembly_percent: z.number().optional().default(0),
    /** Exibir linhas de trecho por local na tabela. */
    quote_show_sections: z.boolean().optional().default(false),
    quote_note_above: z.string().optional().default(""),
    quote_note_below: z.string().optional().default(""),

    // Timestamps
    created_at: z.string().optional(),
    updated_at: z.string().optional(),

    // Relations
    locations: z.array(budgetLocationSchema).optional(),
});

// --- TypeScript Types derived from Zod ---

export type BudgetItem = z.infer<typeof budgetItemSchema> & {
    // Relationships for UI display
    product_code?: string;
    product_name?: string;
    product_unit?: string;
    product_image?: string;
};

export type BudgetSection = z.infer<typeof budgetSectionSchema>;
export type BudgetLocation = z.infer<typeof budgetLocationSchema>;
export type Budget = z.infer<typeof budgetSchema>;

// Helper for UI Tree Structure
export type BudgetTree = Budget & {
    locations: (BudgetLocation & {
        sections: (BudgetSection & {
            items: BudgetItem[];
        })[];
    })[];
};
